modified workflows

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,14 +1,10 @@
 name: Run Pytest
 
 on:
-  push:
-    branches: [main, development]
-    paths:
-      - '**/*.py'  # Trigger only when Python files are changed
-  pull_request:
-    branches: [main, development]
-    paths:
-      - '**/*.py'  # Trigger only when Python files are changed
+  workflow_run:
+    workflows: ["Upload Model"]
+    types:
+      - completed
 
 jobs:
   test:
@@ -27,9 +23,6 @@ jobs:
         python -m pip install --upgrade pip
         pip install -r requirements.txt
 
-    - name: Show current directory
-      run: pwd
-
     - name: Restore pretrained model from cache
       id: cache-model
       uses: actions/cache@v4
@@ -44,12 +37,30 @@ jobs:
         name: trained-model
         path: src/models
 
+    - name: Check if model file exists
+      id: check_model
+      run: |
+        if [ -f "src/models/model.pkl" ]; then
+          echo "model_exists=true" >> $GITHUB_OUTPUT
+        else
+          echo "❌ Model file not found!"
+          echo "model_exists=false" >> $GITHUB_OUTPUT
+        fi
+
     - name: Start MongoDB
+      if: steps.check_model.outputs.model_exists == 'true'
       uses: supercharge/mongodb-github-action@1.12.0
       with: 
         mongodb-version: '6.0.5'
 
     - name: Run tests
+      if: steps.check_model.outputs.model_exists == 'true'
       env: 
         MONGODB_URI: mongodb://localhost:27017
       run: pytest
+
+    - name: Fail if model is missing
+      if: steps.check_model.outputs.model_exists != 'true'
+      run: |
+        echo "⚠️ model.pkl not found after checking both cache and artifacts."
+        exit 1
